name: iOS Unit & UI Tests with Code Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ios-tests:
    name: Run Tests and Collect Coverage
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Show available destinations
        run: |
          xcodebuild -project DogLand.xcodeproj \
            -scheme DogLand \
            -showdestinations

      - name: Run All Tests Using Test Plan with Code Coverage
        run: |
          xcodebuild \
            -project DogLand.xcodeproj \
            -scheme DogLand \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            -enableCodeCoverage YES \
            clean test \
            -resultBundlePath TestResults

      - name: Extract Coverage Report
        run: |
          xcrun xccov view --report --json TestResults.xcresult > code-coverage.json

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: Code Coverage Report
          path: code-coverage.json

      - name: Upload Raw Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Raw Test Results
          path: |
            TestResults.xcresult
