name: iOS Unit & UI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ios-tests:
    name: Run Tests
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Debug project contents
        run: |
          ls -R
          find . -name "*.xcodeproj"
          find . -name "*.swift"


      - name: Run Unit Tests (XCTest) with Code Coverage
        run: |
          xcodebuild \
            -scheme DogLand \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            -enableCodeCoverage YES \
            clean test \
            -only-testing:DogLandTests \
            -resultBundlePath TestResults

      - name: Run UI Tests (XCUITest)
        run: |
          xcodebuild \
            -scheme YourAppScheme \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            test \
            -only-testing:DogLandUITests \
            -resultBundlePath UITestResults
